name: Install, build and test backend

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Maven:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Docker compose up
      run: docker compose up -d
      working-directory: backend

    - name: Maven clean install
      run: mvn clean install
      working-directory: backend

    - name: Maven test
      run: mvn test
      working-directory: backend

    - name: Docker compose down
      run: docker compose down
      working-directory: backend